# Site settings
title: 一步一步学python-91python
email: hipeace86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.91python.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  hipeace86
weibo:    91python
github:   hipeace86
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname



# Google Analytics
# google_analytics: tracking_ID

highlighter: pygments

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
