# Site settings
title: 一步一步学python-91python
email: hipeace86[At]Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  记录python学习路上的各种折腾
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.91python.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  hipeace86
weibo:    91python
github:   hipeace86
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname



# Google Analytics
google_analytics: UA-73166429-1

highlighter: rouge

excerpt_separator: ""

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
